blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/cloudandthings/terraform-aws-module-template/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/cloudandthings/terraform-aws-module-template/security/advisories/new
    about: Report security vulnerabilities privately
